### ISSUE TITLE
[Bug] Reset to main menu before game finished

### ISSUE THREAD

**Issue by msrd0** [LuckyTurtleDev/mission2teegarden-b#108]
This happened when one player had reached their flag already but the other player hadn't finished yet.

![20230629_152417.jpg](https://github.com/LuckyTurtleDev/mission2teegarden-b/assets/7853372/f2a6f553-171a-4852-800f-f1f2bc1c46a5)

**Comment by LuckyTurtleDev** [comment]
fixed
